name = "markdown"
version = "0.1.2"
description = "Markdown to HTML conversion for Donna"
licences = ["MIT"]
repository = { type = "github", user = "NikolasSkyl", repo = "markdown" }
links = [{ title = "Docs", href = "https://nikolasskyl.github.io/markdown/" }]

[dependencies]
donna = { git = "https://github.com/donna-lang/donna_stdlib", version = ">=0.3.0 and <1.0.0" }

[dev-dependencies]
unittest = { git = "https://github.com/donna-lang/unittest", version = ">=0.1.0 and <1.0.0" }
